### PR TITLE
Deleted:    archive/docker-compose.yml

### PR DESCRIPTION
**Pull request by abernatskiy**

### CODE REVIEW

**Comment by dzhelezov** [comment]
Why change the db name from `squid` to`postgres`?

**Comment by abernatskiy** [comment]
> Why change the db name from `squid` to`postgres`?

It was supposed to be a change of the password, not of the db name. Thanks for catching. Fixed.

**Review by dzhelezov — APPROVED** [review]

**Comment by jasl** [comment]
https://github.com/subsquid-labs/squid-substrate-template#self-hosted-archive
The readme doc still metion about Self-hosted archive

**Comment by jasl** [comment]
BTW, is there any reason to delete the self-hosting archive? without it, how to do typegen?

**Comment by dzhelezov** [comment]
@abernatskiy

**Comment by abernatskiy** [comment]
Hello @jasl! I removed the file to avoid having to maintain multiple versions. Instructions for self-hosting archives are kept in [this repo](https://github.com/subsquid/substrate-archive-setup) now. If your workflow requires a local archive endpoint, that may help.

If it'd be more convenient for you to have this file here, let me know here and I'll revert the change. Otherwise I'll update the README to point to the central substrate-archive-setup repo.

**Comment by jasl** [comment]
> Hello @jasl! I removed the file to avoid having to maintain multiple versions. Instructions for self-hosting archives are kept in [this repo](https://github.com/subsquid/substrate-archive-setup) now. If your workflow requires a local archive endpoint, that may help.
> 
> If it'd be more convenient for you to have this file here, let me know here and I'll revert the change. Otherwise I'll update the README to point to the central substrate-archive-setup repo.

Update README is good to me

**Comment by abernatskiy** [comment]
[Done](https://github.com/subsquid-labs/squid-substrate-template/commit/77e11e58e76a6056e5d9b50588241f5834183065). Thanks for the catch!

**Pull request merged**
